version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports: ["6379:6379"]

  api:
    build: ./services/api
    env_file: .env
    depends_on: [postgres, redis]
    ports: ["8000:8000"]
    volumes:
      - ./services/api:/app

  worker:
    build: ./services/worker
    env_file: .env
    depends_on: [api, redis]
    volumes:
      - ./services/worker:/app

  web:
    build: ./services/web
    env_file: .env
    depends_on: [api]
    ports: ["5173:5173"]
    volumes:
      - ./services/web:/usr/src/app

volumes:
  pgdata:
